from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
	path('home/<int:id>/', views.MainView.as_view(), name='home'),
    path('home/search/', views.SearchBoardView.as_view(), name='search_board'),
    path('team/create/', views.TeamView.as_view(), name='create'),
    path('team/<int:id>/', views.TeamView.as_view(), name='team'),
    path('board/create/', views.BoardView.as_view(), name='board'),
    path('board/close/<int:board_id>/', views.CloseBoardView.as_view(), name="close_board"),
    path('board/leave/<int:board_id>/', views.LeaveBoardView.as_view(), name="leave_board"),
    path('board/<int:id>', views.BoardView.as_view(), name='board_view'),
    path('board/create/list/<int:board_id>/', views.ListView.as_view(), name='list_create'),
    path('board/create/card/<int:list_id>/', views.TicketView.as_view(), name='card_create'),
    path('board/archive/list/<int:list_id>/',views.ArchiveListView.as_view(), name='archive_list'),
    path('board/archive/view/items/<int:board_id>/', views.ArchivedItemsView.as_view(), name='archived_items'),
    path('board/archive/card/<int:ticket_id>/',views.ArchiveTicketView.as_view(), name='archive_ticket'),
    path('board/unarchive/list/<int:list_id>/', views.UnarchiveListView.as_view(), name='unarchive_list'),
    path('board/unarchive/card/<int:ticket_id>/', views.UnarchiveTicketView.as_view(), name='unarchive_card'),
    path('board/delete/list/<int:list_id>/', views.DeleteListView.as_view(), name='delete_list'),
    path('board/delete/card/<int:ticket_id>/', views.DeleteCardView.as_view(), name='delete_card'),
    path('board/card/change/<int:ticket_id>/<int:lists_id>/', views.UpdateCardListView.as_view(), name='drag_card'),
    path('board/invite/<int:board_id>/', views.InviteToBoardView.as_view(), name='invite_member'),
    path('board/invite/view/', views.BoardInvitesView.as_view(), name='view_invites'),
    path('board/invite/confirm/<int:board_id>/<int:invite_id>/', views.BoardInvitesView.as_view(), name="confirm_invite"),
    path('board/view/members/<int:board_id>/', views.MemberBoardView.as_view(), name="members"),
    path('board/view/card/get/description/<int:ticket_id>/', views.UpdateDescTicketView.as_view(), name="get_desc"),
    path('board/view/card/<int:ticket_id>/',views.TicketView.as_view(), name='ticket_view'),
    path('board/view/card/comment/<int:ticket_id>/', views.CommentView.as_view(), name='ticket_comment'),
    path('board/view/card/description/<int:ticket_id>/', views.UpdateDescTicketView.as_view(), name='ticket_description'),
    path('board/view/card/comment/edit/<int:comment_id>/', views.EditComment.as_view(), name="edit_comment"),
    path('board/view/card/comment/get/<int:comment_id>/',views.CommentView.as_view(),name='get_comment'),
    path('board/view/card/comment/delete/<int:comment_id>/',views.DeleteComment.as_view(),name='delete_comment'),
    path('board/view/card/get/members/<int:ticket_id>/', views.AssignMemberView.as_view(), name='get_assign_member'),
    path('board/view/card/assign/member/<int:user_id>/<int:ticket_id>/', views.AssignMemberView.as_view(), name='assign_member'),
    path('board/view/card/unassign/member/<int:user_id>/<int:ticket_id>/', views.UnassignMemberView.as_view(), name='unassign_member'),
    path('board/view/card/create/progress/<int:ticket_id>/', views.CreateProgressView.as_view(), name='create_progress'),
    path('board/view/card/create/checklist/<int:progress_id>/', views.CreateCheckListView.as_view(), name='create_checklist'),
    path('board/view/card/progress/checklist/done/<int:item_id>/', views.ChecklistDoneView.as_view(), name='check_progress'),
    path('board/view/card/progress/checklist/undone/<int:item_id>/', views.ChecklistUndoneView.as_view(), name='check_progress_undone'),
    path('board/view/card/delete/progress/<int:progress_id>/', views.DeleteChecklistView.as_view(), name="delete_checklist"),
]