# Generated by Django 2.2 on 2019-04-10 07:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190410_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(null=True, upload_to=main.models.ticket_file_upload_path),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.ticket_image_file_upload_path),
        ),
    ]
