# Generated by Django 2.2 on 2019-04-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190412_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
