# Generated by Django 2.2 on 2019-04-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_activities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
