# Generated by Django 2.2 on 2019-04-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acitivity', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('archive_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_list', to='main.List')),
                ('archive_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_ticket', to='main.Ticket')),
                ('curr_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_list', to='main.List')),
                ('new_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_list', to='main.List')),
                ('new_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_ticket', to='main.Ticket')),
                ('prev_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_list', to='main.List')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='main.Ticket')),
            ],
        ),
    ]
