# Generated by Django 2.2 on 2019-04-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='archive_list',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='archive_ticket',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='curr_list',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='new_list',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='new_ticket',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='prev_list',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='ticket',
        ),
    ]
