# Generated by Django 2.2 on 2019-04-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190415_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='acitivity',
            new_name='activity',
        ),
    ]
