# Generated by Django 2.2 on 2019-04-16 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
