# Generated by Django 2.2 on 2019-04-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_checklist_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='lists',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
