# Generated by Django 2.2 on 2019-04-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_checklist_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
